server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug